---
driver:
  name: vagrant

provisioner:
  name: ansible_push
  ansible_config: test/ansible.cfg
  verbose: vv
  diff: true
  chef_bootstrap_url: nil

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    provisioner:
      playbook: test/playbooks/default.yml
