---
- name: create alertmanager config directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ alertmanager_config_dir }}"

- name: create alertmanager data directory
  file:
    path: "{{ alertmanager_data_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- include: component_install.yml
  prometheus_component_name: alertmanager
  prometheus_component_service_name: alertmanager
  prometheus_component_version: "{{ alertmanager_version }}"
  prometheus_component_checksum: "{{ alertmanager_checksum }}"
  prometheus_component_install_dir: "{{ alertmanager_bin_dir }}"
  prometheus_component_service_args: "{% for k, v in (alertmanager_default_flags | combine(alertmanager_flags)).iteritems() %}-{{ k }}={{ v }} {% endfor %}"

- name: write alertmanager config file
  template:
    src: "{{ alertmanager_config_src }}"
    dest: "{{ alertmanager_config_dir}}/alertmanager.yml"
    owner: root
    group: root
    mode: 0644
    validate: "{{ alertmanager_bin_dir }}/current/amtool check-config %s"
  notify:
    - reload alertmanager

- name: manage alertmanager service
  service:
    name: alertmanager
    state: "{{ alertmanager_service_enabled | ternary('started', 'stopped') }}"
    enabled: "{{ alertmanager_service_enabled }}"
