---
- name: create alertmanager config directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ prometheus_group }}"
    mode: 0755
  with_items:
    - "{{ alertmanager_config_dir }}"
    - "{{ alertmanager_template_dir }}"

- name: create alertmanager data directory
  file:
    path: "{{ alertmanager_data_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- import_tasks: component_install.yml
  vars:
    prometheus_component_name: alertmanager
    prometheus_component_service_name: alertmanager
    prometheus_component_version: "{{ alertmanager_version }}"
    prometheus_component_checksum: "{{ alertmanager_checksum }}"
    prometheus_component_install_dir: "{{ alertmanager_bin_dir }}"
    prometheus_component_service_args: "{% for k, v in (alertmanager_default_flags | combine(alertmanager_flags)).iteritems() %}{{ alertmanager_flag_prefix }}{{ k }}={{ v }} {% endfor %}"

- name: get list of current alertmanager template files
  find:
    paths: "{{ alertmanager_template_dir }}"
  register: _alertmanager_templates_found

- name: remove unmanaged alertmanager template files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ _alertmanager_templates_found.files | map(attribute='path') | difference(alertmanager_template_file_paths) }}"
  notify:
    - reload alertmanager

- name: copy alertmanager template files from playbook directory
  copy:
    src: "{{ alertmanager_template_src_dir }}/{{ item }}"
    dest: "{{ alertmanager_template_dir }}/{{ item }}"
    owner: root
    group: "{{ prometheus_group }}"
    mode: "{{ promethus_config_file_mode }}"
  with_items: "{{ alertmanager_templates }}"
  notify:
    - reload alertmanager

- name: write alertmanager config file
  template:
    src: "{{ alertmanager_config_src }}"
    dest: "{{ alertmanager_config_dir}}/alertmanager.yml"
    owner: root
    group: "{{ prometheus_group }}"
    mode: "{{ promethus_config_file_mode }}"
    validate: "{{ alertmanager_bin_dir }}/current/amtool check-config %s{% if alertmanager_version is version('0.13.0', '>=') %} --alertmanager.url=localhost:9093{% endif %}"
  notify:
    - reload alertmanager

- name: manage alertmanager service
  service:
    name: alertmanager
    state: "{{ alertmanager_service_enabled | ternary('started', 'stopped') }}"
    enabled: "{{ alertmanager_service_enabled }}"
