---
- include: component_install.yml
  prometheus_component_name: consul_exporter
  prometheus_component_service_name: consul_exporter
  prometheus_component_version: "{{ consul_exporter_version }}"
  prometheus_component_install_dir: "{{ consul_exporter_bin_dir }}"
  prometheus_component_checksum: "{{ consul_exporter_checksum }}"
  prometheus_component_service_args: "{% for k, v in consul_exporter_flags.iteritems() %}--{{ k }}=\"{{ v }}\" {% endfor %}"

- name: manage consul_exporter service
  service:
    name: consul_exporter
    state: "{{ prometheus_service_enabled | ternary('started', 'stopped') }}"
    enabled: "{{ prometheus_service_enabled }}"
