---
- include: component_install.yml
  prometheus_component_name: node_exporter
  prometheus_component_service_name: node_exporter
  prometheus_component_version: "{{ node_exporter_version }}"
  prometheus_component_install_dir: "{{ node_exporter_bin_dir }}"
  prometheus_component_checksum: "{{ node_exporter_checksum }}"
  prometheus_component_service_args: "{% for c in node_exporter_collectors_enabled %}--collector.{{ c }} {% endfor %}{% for c in node_exporter_collectors_disabled %}--no-collector.{{ c }} {% endfor %} {% for k, v in node_exporter_flags.iteritems() %}--{{ k }}=\"{{ v }}\" {% endfor %}"

- name: manage node_exporter service
  service:
    name: node_exporter
    state: "{{ prometheus_service_enabled | ternary('started', 'stopped') }}"
    enabled: "{{ prometheus_service_enabled }}"
