---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart prometheus
  service:
    name: prometheus
    state: restarted
  when: prometheus_service_enabled

- name: reload prometheus
  service:
    name: prometheus
    state: reloaded
  when: prometheus_service_enabled

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted
  when: alertmanager_service_enabled

- name: reload alertmanager
  service:
    name: alertmanager
    state: reloaded
  when: alertmanager_service_enabled
